# -*- coding: utf-8 -*-
"""recom_category.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ea3oM39e_CgqEfTQd_zE1pKPILRw9CW6
"""

import numpy as np 
import pandas as pd

dataset = pd.read_csv("inspire/mlmodel/posts.csv")

dataset.head()

category_content = dataset.drop(['__v','_id','imageurl','organization','socialmedia'], axis=1)

print(category_content)

content = category_content.drop(['category'], axis=1)

print(content)

import sklearn
from sklearn.feature_extraction.text import TfidfVectorizer 
tfidf = TfidfVectorizer(stop_words='english')
category_content['content'] = category_content['content'].fillna('')
tfidfMatrix = tfidf.fit_transform(category_content['content'])
tfidfMatrix.shape

from sklearn.metrics.pairwise import linear_kernel 
cos_similarity= linear_kernel(tfidfMatrix, tfidfMatrix)

indices = pd.Series(category_content.index, index=category_content['category']).drop_duplicates()

def get_recommendations(category, cos_similarity=cos_similarity):
    idx = indices[category]
    sim_scores = list(enumerate(cos_similarity[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:11]
    category_indices = [i[0] for i in sim_scores]
    return category_content['category'].iloc[category_indices]

# get_recommendations('startup')